server.port=8080



eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:9090/eureka/

resilience4j.ratelimiter.instances.inventoryRateLimiter.limit-for-period=2
resilience4j.ratelimiter.instances.inventoryRateLimiter.limit-refresh-period=10s
resilience4j.ratelimiter.instances.inventoryRateLimiter.timeout-duration=2s

custom.message=Hello Updated Order Service

spring.datasource.url=jdbc:mysql://localhost:3306/order_db
spring.datasource.username=root
spring.datasource.password=ROOT

resilience4j.retry.instances.inventoryRetry.max-attempts=3
resilience4j.retry.instances.inventoryRetry.wait-duration=2s


resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.minimum-number-of-calls=2
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.sliding-window-size=2
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.wait-duration-in-open-state=10s